### ISSUE TITLE
use mongodb 2.1.4

### ISSUE THREAD

**Issue by mvaragnat** [ratson/monkii#2]
Thank you for providing Monkii - very useful.

Could you consider upgrading mongodb dependency to the latest? It currently forces down to mongodb 2.0

**Comment by ratson** [comment]
Glad to hear that you find this useful. 😀

The constraint in fact is introduced by `mongoskin`.
I have sent a [pull request](https://github.com/kissjs/node-mongoskin/pull/188) to fix that.
If you can't wait, you could also use `npm` v3 and ignore the warning.

Update:
The pull request fails the authentication tests, need to wait until https://github.com/kissjs/node-mongoskin/issues/163 is resolved.

**Comment by ratson** [comment]
Released v1.2.0 with mongodb v2.1 support.
