### ISSUE TITLE
issues with MongoError on collection.insert and collection.update

### ISSUE THREAD

**Issue by heartnetkung** [ratson/monkii#4]
The issue is that when Mongo Error occurs `collection.insert` and `collection.update` has an internal error and not calling Promise.reject properly. Thus, causing the promise to never return.

The fix and test case for `collection.insert`
https://github.com/heartnetkung/monkii/commit/0b5e641769f20597f62b4030684355cc54ca5b87

The fix and test case for `collection.insert`
https://github.com/heartnetkung/monkii/commit/1644ccdc89891f87bf03d59532a7f3dee34949ac

ps. Thank you for the fork. You save me quite a trouble. I had the problem with the dependencies as well :)
ps.2 In case you are interested, I also add support for `collection.aggregation` and some minor improvements as well.

**Comment by ratson** [comment]
Cool, would you send pull requests about the changes?
I am happy to review and merge them.

**Comment by heartnetkung** [comment]
#6 merged and closed
