### ISSUE TITLE
Result is null when .update({...}) is called

### ISSUE THREAD

**Issue by JoelParke** [ratson/monkii#8]
Thanks for this update!!
With the shift from monk to monkii
I am seeing a result of null! instead of 1 in my code:

```
return new Promise(function (resolve, reject) {
    ...
     users.update({_id: self.userData._id}, { $set: self.userData}, {upsert: true })
     .success(function (result) {
        log('***************', result);
        //assert(result === 1);
       ...
       ...
     })
    .error(function (error) {
         error(error);
         reject(error);
     });
});
```

This happens in several places.  The only change I made was to shift to monkii.  
In attempting to debug the Collection.prototype.update code lines: 175-181:

```
      debug('%s update %j with %j', this.name, search, update);
      promise.query = { query: search, update: update };
      this.col.update(search, update, opts, function(err, result) {
         callback(err, opts.multi ? result && result.result.n : null)
 });
 return promise;
```

Things look reasonable, and I do see: 

```
result = CommandResult
result.result.n = 1 
result.result.nModified = 1
result.ok = 1 
```

But the result I get back is null?  
Looking into this further, I notice that opts.multi is undefined here.
If I call with { ... multi:false ... } again I get a null result.
If I call with { ... multi:true ... } I get a 1 result as expected.

Looking in mongodb docs, I see:
multi   boolean Optional. If set to true, updates multiple documents that meet the query criteria. If set to false, updates one document. The default value is false. For additional information, see Multi Parameter.

So it seems that in either case I should be back a RESULT and not NULL!
Although in my original call I expect there to be only ONE match in the query criteria so that multi:false or multi:true should not make any difference. 

Please let me know your thoughts.  For now I have modified my code to pass multi:true in my calls.

Thanks,
Joel Parke

**Comment by ratson** [comment]
@JoelParke Thanks for reporting the problem.

I created [a branch](https://github.com/ratson/monkii/tree/fix-null-update) to test the problem your have described, and don't see the issue. Would you checkout the branch and run `npm test` to see if having different result?

Did you try `.then().catach()` instead of `.success().error()`? Were they having the same result?

**Comment by JoelParke** [comment]
I added:

```
db.options.multi = true;
```

to my code and the problem went away.  So ? what is multi set to in your test code ?
I will attempt to check this tomorrow.  

Thanks!

**Comment by ratson** [comment]
@JoelParke I did not set `multi = true` and able to get back `1`
You can see the change of branch in https://github.com/ratson/monkii/commit/d8e1fae8bdadb63b712452dcf1b40662ff5e1226

I've made you a collaborator on the project so you can add test and push the fix yourself.

**Comment by JoelParke** [comment]
I just hit another spot in my code, where despite having the db.options.multi = true, I had to modify the code with:

```
   lists.updateById(self.listData._id,
              { $set: self.listData,
                $unset: { bSortUp: "", sortType: ""}},
              { multi:true, upsert: true })
  .success(function (result) {
    log('************************', result);
    assert(result === 1);
```

where I explicitly had to set multi:true.  

I am still looking into this, but I have have had a host of other issues, so haven't yet had time to find the heart of the issue.  But I am working on it...

Thanks.

**Comment by JoelParke** [comment]
I just tried this with:

```
    lists.updateById(self.listData._id,
              { $set: self.listData,
                $unset: { bSortUp: "", sortType: ""}},
              { multi:false, upsert: true })
  .then(function (result) {
    log('************************', result);
    assert(result === 1);
    apiSocket.postSave('list', clientId, userData._id, updatedListData);
    if (userData.sharingWithUsers) userData.sharingWithUsers.forEach(function (su) {
      apiSocket.postSave('list', clientId, su.userId, updatedListData);
    });
    if (userData.sharingFromUsers) userData.sharingFromUsers.forEach(function (su) {
      apiSocket.postSave('list', clientId, su.userId, updatedListData);
    });
    resolve(result);
  })
  .catch(function (err) {
    error(err);
    reject(err);
  });
```

And I see the same error:

```
2016-06-14T06:53:15-0600 <log> list.model.js:148 () ************************ null
2016-06-14T06:53:15-0600 <error> list.model.js:160 (EventEmitter.<anonymous>) {       [AssertionError: false == true]
    name: 'AssertionError',
    actual: false,
    expected: true,
    operator: '==',
    message: 'false == true',
    generatedMessage: true }
2016-06-14T06:53:15-0600 <error> list.controller.js:214 () ERROR:AssertionError: false == true
Unhandled rejection Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/home/joel/workspace/Tracker2/node_modules/express/lib/response.js:718:10)
```

So on the one hand, it's probably good that (.then)(.catch) behave the same as (.success)(.error) but the bug is still there....

Thanks,
Joel

**Comment by ratson** [comment]
Close as it refer to old version.
